### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by giuseppefg83**
add missing package locales-all

### CODE REVIEW

**Comment by zengxs** [comment]
Hi @giuseppefg83,

Thank you for your contribution to the gitlab-arm64 project with your pull request. I truly appreciate your effort to enhance the Dockerfile by suggesting the addition of the `locales-all` package.

Before I can merge your PR, could you please provide some more insights into why this package is considered essential for the arm64 architecture? The aim of this project is to ensure that the behavior of the arm64 image is fully consistent with the [official x86-64 version](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/docker/Dockerfile), which currently does not include the `locales-all` package in the Dockerfile.

If you could elucidate the specific needs that this package addresses for arm64 users, it would greatly help me understand its importance. This, in turn, would allow us to make an informed decision on how to maintain the project's objective while accommodating the unique aspects of the arm64 environment.

Thank you once again for your participation and understanding. I'm looking forward to learning more about your proposal.

**Comment by JJJ** [comment]
The most relevant possibility that I could find was here:

https://github.com/Icinga/docker-icingaweb2/pull/30

(I have no idea if including it here would improve GitLab's build times though. If I'm guessing, it seems unlikely, as `locales` is already on the parent machine.)

**Comment by zengxs** [comment]
@JJJ
I share the concern that introducing locales-all might have unintended side effects, as the primary goal of this project is to mirror the behavior of the official x86-64 Docker image. The addition of locales-all could potentially result in scripts outputting non-ASCII characters in some instances, leading to inconsistencies. Unless there are clear advantages to including this package, it might not justify the potential risks.

**Comment by JJJ** [comment]
Suspicious!

**Pull request closed without merging**
